# Generated by Django 3.2.2 on 2021-05-10 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_profile_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='button_value',
            field=models.CharField(default=django.utils.timezone.now, max_length=55),
            preserve_default=False,
        ),
    ]
