# Generated by Django 3.2.2 on 2021-05-10 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_message_button_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='button_value',
        ),
        migrations.AddField(
            model_name='profile',
            name='button_value',
            field=models.CharField(default=django.utils.timezone.now, max_length=55),
            preserve_default=False,
        ),
    ]
